export const irregularVerbs: Array<[string, string]> = [
  ["Pedir", "to ask for or to order"],
  ["Elegir", "to choose or elect, elección"],
  ["Conseguir", "to obtain, or attain or to get"],
  ["Freír", "to fry, huevo frito, papas fritas"],
  ["tocino", "bacon"],
  ["Medir", "to measure, or how tall are you ?Cuanto mides? "],
  ["Reír/ Reírse", "to laugh, Yo rio"],
  ["Repetir", "to repeat"],
  ["Seguir", "to follow, or continue"],
  ["Sonreír", "to smile"],
  ["Empezar", "to start"],
  [
    "Regar",
    "to water, riego = I water, regamos = we water, yo riego el pasto = i water the grass",
  ],
  ["Ambos", "both"],
  ["Fregar", "to scrub"],
  ["Pensar", "to think"],
  ["Cerrar", "to close"],
  ["Entender", "to understand"],
  ["Perder", "to lose"],
  ["Mentir", "to lie"],
  ["Preferir", "to prefer"],
  ["Venir", "to come"],
  ["Despertar", "to wake up > Despierto"],
];
